### ISSUE TITLE
Refactor `Gemfile` and `.gemspec` to remove `rails` dependency?

### ISSUE THREAD

**Issue by nimmolo** [rails/requestjs-rails#13]
Does this gem depend on all of Rails? As far as I can tell it only uses `railties`. I know it does depend on `webpacker` OR `importmap` also.

Our app skips importing significant parts of rails for efficiency because we don't use them, namely
```
activestorage
actioncable 
actionmailbox
actiontext 
```

and I believe this is not an uncommon practice. `requestjs-rails` would be our only dependency requiring all of `rails`. 

An alternative is to just hand-code what this gem does in our js requests.  But if the Gemfile/gemspec can be rewritten to only require `railties` or any other gems that `requestjs-rails` depends on, i'd be happy to submit a PR.

**Comment by marcelolx** [comment]
Yeah it does not depend on all of Rails, feel free to send a PR with the changes needed!

**Comment by nimmolo** [comment]
Comin' up... 
do you prefer the PR to come from my repo, or a new branch here?

**Comment by marcelolx** [comment]
fork -> make changes -> open pr against this repository (I don't think you will able to create a branch here if you don't have the permissions to do so)

**Comment by marcelolx** [comment]
I will push a release by the EOW. Meanwhile, pin to the main branch in your Gemfile :rais

**Comment by nimmolo** [comment]
Thank you much!

**Comment by nimmolo** [comment]
Hi @marcelolx  - do you think you'll push a release soon?

**Comment by marcelolx** [comment]
@nimmolo https://github.com/rails/requestjs-rails/releases/tag/v0.0.11, thanks for the ping!
